name: ci

on: [ push ]

jobs:
  build:
    runs-on : ${{ matrix.os }}
    strategy:
      matrix:
          os: [ windows-latest ]
          
    steps :     
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache
      id  : cache
      uses: actions/cache@v4
      with:
          path: |
            ~/.conan
            ${{ github.workspace }}/../Qt/5.15.2/msvc2019_64
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name : Setup Qt Env
      if   : steps.cache.outputs.cache-hit == 'true'
      shell: pwsh
      env  : 
        QTDIR: ${{ github.workspace }}/../Qt/5.15.2/msvc2019_64
      run  : echo ${env:QTDIR}

    - name: Install Qt
      if  : steps.cache.outputs.cache-hit != 'true'
      uses: jurplel/install-qt-action@v3
      with:
          version: "5.15.2"
