name: ci

on: [ push ]

jobs:
  build:
    runs-on : ${{ matrix.os }}
    strategy:
      matrix:
          os: [ windows-latest ]
          
    steps :     
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache Conan
      id  : cache-conan
      uses: actions/cache@v1
      with:
          path: ~/.conan
          key: ok-edu-desktop-windows-conan

    - name: Cache Qt
      id  : cache-qt
      uses: actions/cache@v1
      with:
          key: ok-edu-desktop-windows-qt
          path: ${{ github.workspace }}/../Qt/5.15.2/msvc2019_64

    - if  : ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
      name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - if  : ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
      name: Install Conan
      run : |
        pip install conan==1.59
        conan install ${{ github.workspace }} -s compiler.runtime=MT --build=missing

    - if  : ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
      name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
          version: "5.15.2"

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
          arch: "amd64"

    - name: Configure CMake
      run : | 
        cp -r ~/.conan ${{ github.workspace }}/build/deps
        cmake -B ${{ github.workspace }}/build -G Ninja -DCMAKE_BUILD_TYPE=Release -DQT_DIR=${{ github.workspace }}/../Qt/5.15.2/msvc2019_64 -DLINK_STATIC_QT=OFF
