name: ci

on: [ push ]

jobs:
  build:
    runs-on : ${{ matrix.os }}
    strategy:
      matrix:
          os: [ windows-latest ]
          
    steps :     
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache
      id  : cache
      uses: actions/cache@v1
      with:
          path: "~/.conan"
          key: ok-edu-desktop-windows1

    - if  : ${{ steps.cache.outputs.cache-hit != 'true' }}
      name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - if  : ${{ steps.cache.outputs.cache-hit != 'true' }}
      name: Install Conan
      run : |
        pip install conan==1.59
        conan install ${{ github.workspace }} -s compiler.runtime=MT --build=missing
