name: ci

on: [ push ]

jobs:
  build:
    runs-on : ${{ matrix.os }}
    strategy:
      matrix:
          os: [ windows-latest ]
          
    steps :     
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache
      id  : cache
      uses: actions/cache@v1
      with:
          key: ok-edu-desktop-${{ runner.os }}
          path: ${{ github.workspace }}/../Qt/5.15.2/msvc2019_64

    - if   : ${{ steps.cache.outputs.cache-hit == 'true' }}
      name : Setup Qt Env
      shell: pwsh
      env  : 
        QTDIR: ${{ github.workspace }}/../Qt/5.15.2/msvc2019_64
      run  : echo ${env:QTDIR}

    - if  : ${{ steps.cache.outputs.cache-hit != 'true' }}
      name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
          version: "5.15.2"
