name: ci

on: [ push ]

jobs:
  build:
    runs-on : ${{ matrix.os }}
    strategy:
      matrix:
          os: [ windows-latest ]
          
    steps :     
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Cache
      id  : cache
      uses: actions/cache@v4
      env :
          cache-name: cache-qt
      with:
          path: ${{ github.workspace }}/../Qt/5.15.2/msvc2019_64
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

    - if   : ${{ steps.cache.outputs.cache-hit == 'true' }}
      name : Setup Qt Env
      shell: pwsh
      env  : 
        QTDIR: ${{ github.workspace }}/../Qt/5.15.2/msvc2019_64
      run  : echo ${env:QTDIR}

    - if  : ${{ steps.cache.outputs.cache-hit != 'true' }}
      name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
          version: "5.15.2"
          
